version: '3.7'

services:
  postgres:
    container_name: nuxt-pg
    image: postgres:latest
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-nuxt-pg}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped

  mailhog:
    container_name: nuxt-mailhog
    image: mailhog/mailhog
    ports:
      - '${SMTP_PORT:-1025}:1025'
      - '${SMTP_WEB_PORT:-8025}:8025'
    restart: unless-stopped

  redis:
    container_name: nuxt-redis
    image: redis:latest
    volumes:
      - ./docker/redis:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

  mondodb:
    container_name: nuxt-mongodb
    image: mongo:latest
    volumes:
      - ./docker/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  postgres:
    driver: local
