packages:
  - ./
  - packages/**
ignoredBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - '@sentry/cli'
  - bcrypt
  - esbuild
  - maplibre-gl
  - protobufjs
  - sharp
  - vnpay
  - vue-demi
onlyBuiltDependencies:
  - better-sqlite3
