import { jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'
import { createInsertSchema, createSelectSchema } from 'drizzle-zod'

export const sysLandingPageTable = pgTable('sys_landing_page', {
  id: uuid('id').defaultRandom().primaryKey().notNull(),
  banner_button: text('banner_button').notNull().default('Get Started'),
  banner_image: text('banner_image'),
  banner_title: text('banner_title').notNull().default('This is a banner title'),
  banner_title_desc: text('banner_title_desc').notNull().default('This is a banner description'),
  contact_us_card_content: text('contact_us_card_content').notNull().default('This is a contact us card content'),
  contact_us_card_heading: text('contact_us_card_heading').notNull().default('This is a contact us card heading'),
  contact_us_card_image: text('contact_us_card_image'),
  contact_us_card_title: text('contact_us_card_title').notNull().default('This is a contact us card title'),
  contact_us_title: text('contact_us_title').notNull().default('This is a contact us title'),
  contact_us_title_desc: text('contact_us_title_desc').notNull().default('This is a contact us description'),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  customer_review_data: jsonb('customer_review_data').default([{
    id: '',
    desc: '',
    main_logo: null,
    logo_dark: null,
    logo_light: null,
    name: '',
    position: '',
    rating: 0,
  }]),
  customer_review_title: text('customer_review_title').notNull().default('This is a customer review title'),
  customer_review_title_desc: text('customer_review_title_desc').notNull().default('This is a customer review description'),
  faq_data: jsonb('faq_data').default([{
    question: '',
    answer: '',
  }]),
  faq_title: text('faq_title').notNull().default('This is a faq title'),
  faq_title_desc: text('faq_title_desc').notNull().default('This is a faq description'),
  feature_data: jsonb('feature_data').default([{
    name: '',
    desc: '',
    icon: '',
  }]),
  feature_title: text('feature_title').notNull().default('This is a feature title'),
  feature_title_desc: text('feature_title_desc').notNull().default('This is a feature description'),
  hero_main_img_dark: text('hero_main_img_dark'),
  hero_main_img_light: text('hero_main_img_light'),
  hero_sub_img_dark: text('hero_sub_img_dark'),
  hero_sub_img_light: text('hero_sub_img_light'),
  hero_title: text('hero_title').notNull().default('This is a hero title'),
  hero_title_button: jsonb('hero_title_button').default([{
    btn_link: '',
    btn_label: '',
    btn_radius: '',
    btn_rippled: false,
    btn_variant: 'flat',
    btn_apend_icon: '',
    btn_background: '',
    btn_prepend_icon: '',
  }]),
  hero_title_desc: text('hero_title_desc').notNull().default('This is a hero description'),
  our_team_data: jsonb('our_team_data').default([{
    id: '',
    name: '',
    position: '',
    image: null,
    background_color: '',
    border_color: '',
    social_networks: {
      facebook: null,
      twitterX: null,
      linkedin: null,
    },
  }]),
  our_team_desc: text('our_team_desc').notNull().default('This is a our team description'),
  our_team_title: text('our_team_title').notNull().default('This is a our team title'),
  pricing_data: jsonb('pricing_data').default([{
    title: '',
    price: 0,
    features: [],
    support_type: '',
    support_medium: '',
    respond_time: '',
  }]),
  pricing_title: text('pricing_title').notNull().default('This is a pricing title'),
  pricing_title_desc: text('pricing_title_desc').notNull().default('This is a pricing description'),
  product_stats: jsonb('product_stats').default([{
    id: '',
    title: '',
    value: 0,
    color: '',
    icon: null,
  }]),
})

export const insertSysLandingPageSchema = createInsertSchema(sysLandingPageTable)
export const selectSysLandingPageSchema = createSelectSchema(sysLandingPageTable)
