import { creditPackageTable } from '../schemas'
import { db } from '../../utils/db'

export async function seedCreditPackages() {
  console.log('Seeding credit packages...')

  return await db.insert(creditPackageTable).values([
    {
      title: 'Basic',
      description: 'Ideal for testing their workflows.',
      price: String(2000),
      amount: String(30),
      currency: 'VND',
      position: String(1),
      features: [
        'Homelab servers',
        '96.69% uptime',
        'Recommended for development purposes',
        'Customer support',
        '1 vCPU, 1GB RAM, 8GB SSD',
        'Unlimited bandwidth',
        'Private VPS',
        'Free sub-domain',
      ],
      created_at: new Date(),
    },
    {
      title: 'Standard',
      description: 'Great for small-scale automation needs.',
      price: String(6900),
      amount: String(69),
      currency: 'VND',
      position: String(2),
      features: [
        'Homelab servers',
        '96.69% uptime',
        'Recommended for development purposes',
        'Customer support',
        '1 vCPU, 2GB RAM, 15GB SSD',
        'Unlimited bandwidth',
        'Private VPS',
        'Custom domain',
      ],
      created_at: new Date(),
    },
    {
      title: 'Pro',
      description: 'Enhanced performance for serious automation.',
      price: String(9600),
      amount: String(96),
      currency: 'VND',
      position: String(3),
      features: [
        'Homelab servers',
        '96.69% uptime',
        'Recommended for development purposes',
        'Customer support',
        '2 vCPU, 4GB RAM, 20GB SSD',
        'Unlimited bandwidth',
        'Private VPS',
        'Custom domain',
      ],
      created_at: new Date(),
    },
    {
      title: 'Premium',
      description: 'Ultimate power for complex workflows.',
      price: String(16900),
      amount: String(169),
      currency: 'VND',
      position: String(4),
      features: [
        'Homelab servers',
        '96.69% uptime',
        'Recommended for development purposes',
        'Customer support',
        '4 vCPU, 8GB RAM, 25GB SSD',
        'Unlimited bandwidth',
        'Private VPS',
        'Custom domain',
      ],
      created_at: new Date(),
    },
    {
      title: 'Solution',
      description: 'We solve your company problems by leveraging our expertise on n8n automation.',
      price: String(0),
      amount: String(0),
      currency: 'VND',
      position: String(5),
      features: [
        'Custom automation solutions',
        'Dedicated support team',
        'Tailored workflow design',
        'Integration with existing systems',
        'Scalable infrastructure',
        'Performance optimization',
        'Security and compliance',
        'Training and onboarding',
      ],
      created_at: new Date(),
    },
    {
      title: 'Enterprise',
      description: 'Unlimited resource for your enterprise-scale automation.',
      price: String(0),
      amount: String(0),
      currency: 'VND',
      position: String(6),
      features: [
        '99.99% uptime',
        'Recommended for enterprise purposes',
        'Priority customer support',
        'On-demand vCPU, RAM, SSD',
        'Unlimited bandwidth',
        'Private VPS',
        'Custom domain',
        'Scalable infrastructure',
        'Performance optimization',
        'Security and compliance',
        'Training and onboarding',
      ],
      created_at: new Date(),
    },
  ]).returning()
}
