CREATE TABLE IF NOT EXISTS "sys_landing_page" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"banner_button" text NOT NULL,
	"banner_image" text,
	"banner_title" text NOT NULL,
	"banner_title_desc" text NOT NULL,
	"contact_us_card_content" text NOT NULL,
	"contact_us_card_heading" text NOT NULL,
	"contact_us_card_image" text,
	"contact_us_card_title" text NOT NULL,
	"contact_us_title" text NOT NULL,
	"contact_us_title_desc" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"customer_review_data" jsonb,
	"customer_review_title" text NOT NULL,
	"customer_review_title_desc" text,
	"faq_data" jsonb,
	"faq_title" text NOT NULL,
	"faq_title_desc" text NOT NULL,
	"feature_data" jsonb,
	"feature_title" text NOT NULL,
	"feature_title_desc" text,
	"hero_main_img_dark" text,
	"hero_main_img_light" text,
	"hero_sub_img_dark" text,
	"hero_sub_img_light" text,
	"hero_title" text NOT NULL,
	"hero_title_button" jsonb NOT NULL,
	"hero_title_desc" text NOT NULL,
	"our_team_data" jsonb,
	"our_team_desc" text NOT NULL,
	"our_team_title" text NOT NULL,
	"pricing_data" jsonb,
	"pricing_title" text NOT NULL,
	"pricing_title_desc" text NOT NULL,
	"product_stats" jsonb
);
