create table "public"."user_devices" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid default gen_random_uuid(),
    "token_device" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."user_devices" enable row level security;

CREATE UNIQUE INDEX user_devices_pkey ON public.user_devices USING btree (id);

alter table "public"."user_devices" add constraint "user_devices_pkey" PRIMARY KEY using index "user_devices_pkey";

alter table "public"."user_devices" add constraint "public_user_devices_user_id_fkey" FOREIGN KEY (user_id) REFERENCES sys_users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_devices" validate constraint "public_user_devices_user_id_fkey";

grant delete on table "public"."user_devices" to "anon";

grant insert on table "public"."user_devices" to "anon";

grant references on table "public"."user_devices" to "anon";

grant select on table "public"."user_devices" to "anon";

grant trigger on table "public"."user_devices" to "anon";

grant truncate on table "public"."user_devices" to "anon";

grant update on table "public"."user_devices" to "anon";

grant delete on table "public"."user_devices" to "authenticated";

grant insert on table "public"."user_devices" to "authenticated";

grant references on table "public"."user_devices" to "authenticated";

grant select on table "public"."user_devices" to "authenticated";

grant trigger on table "public"."user_devices" to "authenticated";

grant truncate on table "public"."user_devices" to "authenticated";

grant update on table "public"."user_devices" to "authenticated";

grant delete on table "public"."user_devices" to "service_role";

grant insert on table "public"."user_devices" to "service_role";

grant references on table "public"."user_devices" to "service_role";

grant select on table "public"."user_devices" to "service_role";

grant trigger on table "public"."user_devices" to "service_role";

grant truncate on table "public"."user_devices" to "service_role";

grant update on table "public"."user_devices" to "service_role";



