create table "public"."sys_faq_categories" (
    "id" smallint generated by default as identity not null,
    "title" text,
    "icon" text,
    "subtitle" text
);


alter table "public"."sys_faq_categories" enable row level security;

alter table "public"."sys_faqs" drop column "icon";

alter table "public"."sys_faqs" drop column "questions";

alter table "public"."sys_faqs" drop column "subtitle";

alter table "public"."sys_faqs" drop column "title";

alter table "public"."sys_faqs" add column "answer" text;

alter table "public"."sys_faqs" add column "category_id" smallint;

alter table "public"."sys_faqs" add column "question" text;

CREATE UNIQUE INDEX sys_faq_categories_pkey ON public.sys_faq_categories USING btree (id);

alter table "public"."sys_faq_categories" add constraint "sys_faq_categories_pkey" PRIMARY KEY using index "sys_faq_categories_pkey";

alter table "public"."sys_faqs" add constraint "public_sys_faqs_category_id_fkey" FOREIGN KEY (category_id) REFERENCES sys_faq_categories(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sys_faqs" validate constraint "public_sys_faqs_category_id_fkey";

grant delete on table "public"."sys_faq_categories" to "anon";

grant insert on table "public"."sys_faq_categories" to "anon";

grant references on table "public"."sys_faq_categories" to "anon";

grant select on table "public"."sys_faq_categories" to "anon";

grant trigger on table "public"."sys_faq_categories" to "anon";

grant truncate on table "public"."sys_faq_categories" to "anon";

grant update on table "public"."sys_faq_categories" to "anon";

grant delete on table "public"."sys_faq_categories" to "authenticated";

grant insert on table "public"."sys_faq_categories" to "authenticated";

grant references on table "public"."sys_faq_categories" to "authenticated";

grant select on table "public"."sys_faq_categories" to "authenticated";

grant trigger on table "public"."sys_faq_categories" to "authenticated";

grant truncate on table "public"."sys_faq_categories" to "authenticated";

grant update on table "public"."sys_faq_categories" to "authenticated";

grant delete on table "public"."sys_faq_categories" to "service_role";

grant insert on table "public"."sys_faq_categories" to "service_role";

grant references on table "public"."sys_faq_categories" to "service_role";

grant select on table "public"."sys_faq_categories" to "service_role";

grant trigger on table "public"."sys_faq_categories" to "service_role";

grant truncate on table "public"."sys_faq_categories" to "service_role";

grant update on table "public"."sys_faq_categories" to "service_role";

create policy "Enable read access for all users"
on "public"."sys_faq_categories"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."sys_faqs"
as permissive
for select
to public
using (true);




