name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - next
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Corepack
        shell: bash
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@thecodeorigin'

      - name: Install Vercel CLI
        run: pnpm add --g vercel@latest

      - name: Install dependencies
        run: pnpm install

      - name: Build Project Artifacts
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Deploy Project Artifacts to Vercel
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
