name: Release to GitHub Packages

on:
  push:
    branches:
      - next

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Corepack
        shell: bash
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Publish to GitHub Packages
        run: pnpm -r publish --publish-branch next --access public --tag next
